import os, time, json, sys
from pathlib import Path
from core.ui import UI, C, W, R, G, B, NC, Y, D
from core.config import load_config

class LootManager:
    def __init__(self, proj_dir):
        # Convert incoming path to Path object just in case
        self.path = Path(proj_dir)
        self.cracked_file = self.path / "CRACKED.txt"
        self.config = load_config()

    def generate_html_report(self):
        html_path = self.path / "TROPHY_ROOM.html"
        handle = self.config.get("handle", "dash")
        
        cracked_data = []
        if self.cracked_file.exists():
            with open(self.cracked_file, 'r') as f:
                for line in f:
                    parts = line.strip().split(':')
                    if len(parts) >= 2:
                        cracked_data.append({"essid": parts[0], "key": parts[1]})

        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Nighthawk Trophy Room</title>
            <style>
                body {{ background-color: #0a0a0a; color: #00ff00; font-family: 'Courier New', monospace; padding: 40px; }}
                h1 {{ border-bottom: 2px solid #00ff00; padding-bottom: 10px; }}
                .card {{ border: 1px solid #333; background: #111; padding: 20px; margin-bottom: 15px; border-radius: 5px; }}
                .key {{ color: #fff; font-weight: bold; font-size: 1.2em; }}
                .footer {{ margin-top: 50px; color: #555; font-size: 0.8em; }}
            </style>
        </head>
        <body>
            <h1>/// MISSION REPORT: {handle} ///</h1>
            <p>TOTAL NETWORKS COMPROMISED: {len(cracked_data)}</p>
            <br>
        """
        
        for data in cracked_data:
            html_content += f"""
            <div class="card">
                <div>TARGET: <strong>{data['essid']}</strong></div>
                <div>DECRYPTED KEY: <span class="key">{data['key']}</span></div>
                <div style="color: #555; font-size: 0.8em;">STATUS: CONFIRMED // WPA2</div>
            </div>
            """
            
        html_content += f"""
            <div class="footer">GENERATED BY NIGHTHAWK SUITE v62.0 // {time.strftime("%Y-%m-%d %H:%M:%S")}</div>
        </body>
        </html>
        """
        
        with open(html_path, "w") as f:
            f.write(html_content)
        
        return html_path

    def run(self):
        while True:
            UI.banner()
            UI.print_box([f"OPERATOR: {self.config.get('handle')}", f"VAULT: {self.cracked_file.name}"], title="LOOT REPOSITORY")
            
            print(f"\n {C}1.{NC} View Raw Credentials")
            print(f" {C}2.{NC} Generate HTML Trophy Room {G}*NEW*{NC}")
            print(f" {C}3.{NC} Clean Garbage Files")
            print(f" {C}4.{NC} Return to Menu")
            
            try: c = input(f"\n {B}Select{NC} {C}»{NC} ").strip()
            except: continue
            
            if c == '1':
                UI.banner()
                if self.cracked_file.exists():
                    print(f"{G}[*] DECRYPTED CREDENTIALS:{NC}\n")
                    with open(self.cracked_file, 'r') as f:
                        for line in f:
                            parts = line.strip().split(':')
                            if len(parts) >= 2:
                                print(f" {W}ESSID:{NC} {C}{parts[0]:<20}{NC} {W}KEY:{NC} {G}{parts[1]}{NC}")
                else: print(f"\n{R}[!] No passwords cracked yet.{NC}")
                input(f"\n{W}Press Enter...{NC}")
            
            elif c == '2':
                path = self.generate_html_report()
                print(f"\n{G}[✔] Trophy Room Generated: {path}{NC}")
                print(f"{W}    Open this file in Firefox/Chrome to see your conquests.{NC}")
                input(f"\n{W}Press Enter...{NC}")

            elif c == '3':
                count = 0
                if self.path.exists():
                    for f in self.path.iterdir():
                        if f.suffix in ['.csv', '.netxml', '.kismet']:
                            try: 
                                f.unlink()
                                count += 1
                            except: pass
                print(f"{G}[✔] Deleted {count} junk files.{NC}")
                time.sleep(1.5)

            elif c == '4': break
